spring:
  application:
    name: resourceserverstudy

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_teste
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: none
